version: '3'
services: 
  pg:
    image: postgres
    restart: always
    volumes:
      - "/usr/local/data/postgresql/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=chuck # 用户名
      - POSTGRES_PASSWORD=chuck@2020 # 数据库密码
      - POSTGRES_DB=pgdb # 数据库名
  app:
    build: .
    restart: always
    volumes:
      - /sys/class/thermal/thermal_zone0:/sys/class/thermal/thermal_zone0
    depends_on: 
      - pg
    ports:
      - "10001:10001"
